name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Nix
        uses: cachix/install-nix-action@616559265b40713947b9c190a8ff4b507b5df49b # v31.10.4
        with:
          github_access_token: ${{ github.token }}

      - name: Configure cachix
        uses: cachix/cachix-action@1eb2ef646ac0255473d23a5907ad7b04ce94065c # v17
        with:
          name: devenv

      - name: Install devenv
        shell: bash
        run: nix profile add --accept-flake-config github:cachix/devenv/latest#devenv
        env:
          NIX_CONFIG: "accept-flake-config = true"

      - name: Run flake checks
        run: nix flake check

  example:
    name: Example
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Nix
        uses: cachix/install-nix-action@616559265b40713947b9c190a8ff4b507b5df49b # v31.10.4
        with:
          github_access_token: ${{ github.token }}

      - name: Configure cachix
        uses: cachix/cachix-action@1eb2ef646ac0255473d23a5907ad7b04ce94065c # v17
        with:
          name: devenv

      - name: Install devenv
        shell: bash
        run: nix profile add --accept-flake-config github:cachix/devenv/latest#devenv
        env:
          NIX_CONFIG: "accept-flake-config = true"

      - name: Build example shell
        working-directory: examples/default
        run: devenv build shell
