name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Devenv
        uses: ./.github/actions/devenv/

      - name: Run flake checks
        run: nix flake check

  example:
    name: Example
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Devenv
        uses: ./.github/actions/devenv/

      - name: Build example shell
        working-directory: examples/default
        run: devenv build shell
